version: 2
jobs:
  build:
    
    working_directory: ~/.circleci

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout
      
      - run: mvn dependency:go-offline
      
      - run: mvn package
      
      - store_test_results:
          path: build/circleci-reports
